export interface IntrusoItem {
    id: string;
    url: string;
    category: string;
    label: string;
}

export const INTRUSO_DATABASE: IntrusoItem[] = [
    // --- CATEGORIA: STRUMENTI DI LAVORO (25 immagini) ---
    { id: 't1', url: 'https://loneboo-images.s3.eu-south-1.amazonaws.com/t1.webp', category: 'TOOLS', label: 'Cassetta Attrezzi' },
    { id: 't2', url: 'https://loneboo-images.s3.eu-south-1.amazonaws.com/t2.webp', category: 'TOOLS', label: 'Cacciavite' },
    { id: 't3', url: 'https://loneboo-images.s3.eu-south-1.amazonaws.com/t3.webp', category: 'TOOLS', label: 'Cacciaviti' },
    { id: 't4', url: 'https://loneboo-images.s3.eu-south-1.amazonaws.com/t4.webp', category: 'TOOLS', label: 'Carriola' },
    { id: 't5', url: 'https://loneboo-images.s3.eu-south-1.amazonaws.com/t5.webp', category: 'TOOLS', label: 'Casco' },
    { id: 't6', url: 'https://loneboo-images.s3.eu-south-1.amazonaws.com/t6.webp', category: 'TOOLS', label: 'Chiave' },
    { id: 't7', url: 'https://loneboo-images.s3.eu-south-1.amazonaws.com/t7.webp', category: 'TOOLS', label: 'Colla' },
    { id: 't8', url: 'https://loneboo-images.s3.eu-south-1.amazonaws.com/t8.webp', category: 'TOOLS', label: 'Guanti' },
    { id: 't9', url: 'https://loneboo-images.s3.eu-south-1.amazonaws.com/t9.webp', category: 'TOOLS', label: 'Livella' },
    { id: 't10', url: 'https://loneboo-images.s3.eu-south-1.amazonaws.com/t10.webp', category: 'TOOLS', label: 'Martello' },
    { id: 't11', url: 'https://loneboo-images.s3.eu-south-1.amazonaws.com/t11.webp', category: 'TOOLS', label: 'Metro' },
    { id: 't12', url: 'https://loneboo-images.s3.eu-south-1.amazonaws.com/t12.webp', category: 'TOOLS', label: 'Metro Legno' },
    { id: 't13', url: 'https://loneboo-images.s3.eu-south-1.amazonaws.com/t13.webp', category: 'TOOLS', label: 'Morsa' },
    { id: 't14', url: 'https://loneboo-images.s3.eu-south-1.amazonaws.com/t14.webp', category: 'TOOLS', label: 'Pennello' },
    { id: 't15', url: 'https://loneboo-images.s3.eu-south-1.amazonaws.com/t15.webp', category: 'TOOLS', label: 'Pennellino' },
    { id: 't16', url: 'https://loneboo-images.s3.eu-south-1.amazonaws.com/t16.webp', category: 'TOOLS', label: 'Pinza' },
    { id: 't17', url: 'https://loneboo-images.s3.eu-south-1.amazonaws.com/t17.webp', category: 'TOOLS', label: 'Rullo' },
    { id: 't18', url: 'https://loneboo-images.s3.eu-south-1.amazonaws.com/t18.webp', category: 'TOOLS', label: 'Sega' },
    { id: 't19', url: 'https://loneboo-images.s3.eu-south-1.amazonaws.com/t19.webp', category: 'TOOLS', label: 'Seghetto' },
    { id: 't20', url: 'https://loneboo-images.s3.eu-south-1.amazonaws.com/t20.webp', category: 'TOOLS', label: 'Spatola' },
    { id: 't21', url: 'https://loneboo-images.s3.eu-south-1.amazonaws.com/t21.webp', category: 'TOOLS', label: 'Spatolina' },
    { id: 't22', url: 'https://loneboo-images.s3.eu-south-1.amazonaws.com/t22.webp', category: 'TOOLS', label: 'Taglierino' },
    { id: 't23', url: 'https://loneboo-images.s3.eu-south-1.amazonaws.com/t23.webp', category: 'TOOLS', label: 'Torcia' },
    { id: 't24', url: 'https://loneboo-images.s3.eu-south-1.amazonaws.com/t24.webp', category: 'TOOLS', label: 'Valigetta' },
    { id: 't25', url: 'https://loneboo-images.s3.eu-south-1.amazonaws.com/t25.webp', category: 'TOOLS', label: 'Chiave Inglese' },

    // --- CATEGORIA: FRUTTI (25 immagini) ---
    { id: 'f1', url: 'https://loneboo-images.s3.eu-south-1.amazonaws.com/f1.webp', category: 'FRUIT', label: 'Ananas' },
    { id: 'f2', url: 'https://loneboo-images.s3.eu-south-1.amazonaws.com/f2.webp', category: 'FRUIT', label: 'Arancia' },
    { id: 'f3', url: 'https://loneboo-images.s3.eu-south-1.amazonaws.com/f3.webp', category: 'FRUIT', label: 'Banana' },
    { id: 'f4', url: 'https://loneboo-images.s3.eu-south-1.amazonaws.com/f4.webp', category: 'FRUIT', label: 'Ciliegia' },
    { id: 'f5', url: 'https://loneboo-images.s3.eu-south-1.amazonaws.com/f5.webp', category: 'FRUIT', label: 'Fragola' },
    { id: 'f6', url: 'https://loneboo-images.s3.eu-south-1.amazonaws.com/f6.webp', category: 'FRUIT', label: 'Kiwi' },
    { id: 'f7', url: 'https://loneboo-images.s3.eu-south-1.amazonaws.com/f7.webp', category: 'FRUIT', label: 'Limone' },
    { id: 'f8', url: 'https://loneboo-images.s3.eu-south-1.amazonaws.com/f8.webp', category: 'FRUIT', label: 'Mela' },
    { id: 'f9', url: 'https://loneboo-images.s3.eu-south-1.amazonaws.com/f9.webp', category: 'FRUIT', label: 'Pera' },
    { id: 'f10', url: 'https://loneboo-images.s3.eu-south-1.amazonaws.com/f10.webp', category: 'FRUIT', label: 'Pesca' },
    { id: 'f11', url: 'https://loneboo-images.s3.eu-south-1.amazonaws.com/f11.webp', category: 'FRUIT', label: 'Prugna' },
    { id: 'f12', url: 'https://loneboo-images.s3.eu-south-1.amazonaws.com/f12.webp', category: 'FRUIT', label: 'Uva' },
    { id: 'f13', url: 'https://loneboo-images.s3.eu-south-1.amazonaws.com/f13.webp', category: 'FRUIT', label: 'Anguria' },
    { id: 'f14', url: 'https://loneboo-images.s3.eu-south-1.amazonaws.com/f14.webp', category: 'FRUIT', label: 'Melone' },
    { id: 'f15', url: 'https://loneboo-images.s3.eu-south-1.amazonaws.com/f15.webp', category: 'FRUIT', label: 'Cocco' },
    { id: 'f16', url: 'https://loneboo-images.s3.eu-south-1.amazonaws.com/f16.webp', category: 'FRUIT', label: 'Mango' },
    { id: 'f17', url: 'https://loneboo-images.s3.eu-south-1.amazonaws.com/f17.webp', category: 'FRUIT', label: 'Papaya' },
    { id: 'f18', url: 'https://loneboo-images.s3.eu-south-1.amazonaws.com/f18.webp', category: 'FRUIT', label: 'Avocado' },
    { id: 'f19', url: 'https://loneboo-images.s3.eu-south-1.amazonaws.com/f19.webp', category: 'FRUIT', label: 'Melograno' },
    { id: 'f20', url: 'https://loneboo-images.s3.eu-south-1.amazonaws.com/f20.webp', category: 'FRUIT', label: 'Fico' },
    { id: 'f21', url: 'https://loneboo-images.s3.eu-south-1.amazonaws.com/f21.webp', category: 'FRUIT', label: 'Lamponi' },
    { id: 'f22', url: 'https://loneboo-images.s3.eu-south-1.amazonaws.com/f22.webp', category: 'FRUIT', label: 'Mirtilli' },
    { id: 'f23', url: 'https://loneboo-images.s3.eu-south-1.amazonaws.com/f23.webp', category: 'FRUIT', label: 'More' },
    { id: 'f24', url: 'https://loneboo-images.s3.eu-south-1.amazonaws.com/f24.webp', category: 'FRUIT', label: 'Albicocca' },
    { id: 'f25', url: 'https://loneboo-images.s3.eu-south-1.amazonaws.com/f25.webp', category: 'FRUIT', label: 'Castagna' },

    // --- CATEGORIA: ANIMALI (25 immagini) ---
    { id: 'a1', url: 'https://loneboo-images.s3.eu-south-1.amazonaws.com/a1.webp', category: 'ANIMAL', label: 'Balena' },
    { id: 'a2', url: 'https://loneboo-images.s3.eu-south-1.amazonaws.com/a2.webp', category: 'ANIMAL', label: 'Cane' },
    { id: 'a3', url: 'https://loneboo-images.s3.eu-south-1.amazonaws.com/a3.webp', category: 'ANIMAL', label: 'Elefante' },
    { id: 'a4', url: 'https://loneboo-images.s3.eu-south-1.amazonaws.com/a4.webp', category: 'ANIMAL', label: 'Giraffa' },
    { id: 'a5', url: 'https://loneboo-images.s3.eu-south-1.amazonaws.com/a5.webp', category: 'ANIMAL', label: 'Granchio' },
    { id: 'a6', url: 'https://loneboo-images.s3.eu-south-1.amazonaws.com/a6.webp', category: 'ANIMAL', label: 'Gufo' },
    { id: 'a7', url: 'https://loneboo-images.s3.eu-south-1.amazonaws.com/a7.webp', category: 'ANIMAL', label: 'Koala' },
    { id: 'a8', url: 'https://loneboo-images.s3.eu-south-1.amazonaws.com/a8.webp', category: 'ANIMAL', label: 'Leone' },
    { id: 'a9', url: 'https://loneboo-images.s3.eu-south-1.amazonaws.com/a9.webp', category: 'ANIMAL', label: 'Mucca' },
    { id: 'a10', url: 'https://loneboo-images.s3.eu-south-1.amazonaws.com/a10.webp', category: 'ANIMAL', label: 'Orso' },
    { id: 'a11', url: 'https://loneboo-images.s3.eu-south-1.amazonaws.com/a11.webp', category: 'ANIMAL', label: 'Panda' },
    { id: 'a12', url: 'https://loneboo-images.s3.eu-south-1.amazonaws.com/a12.webp', category: 'ANIMAL', label: 'Pappagallo' },
    { id: 'a13', url: 'https://loneboo-images.s3.eu-south-1.amazonaws.com/a13.webp', category: 'ANIMAL', label: 'Pinguino' },
    { id: 'a14', url: 'https://loneboo-images.s3.eu-south-1.amazonaws.com/a14.webp', category: 'ANIMAL', label: 'Polpo' },
    { id: 'a15', url: 'https://loneboo-images.s3.eu-south-1.amazonaws.com/a15.webp', category: 'ANIMAL', label: 'Rana' },
    { id: 'a16', url: 'https://loneboo-images.s3.eu-south-1.amazonaws.com/a16.webp', category: 'ANIMAL', label: 'Scimmia' },
    { id: 'a17', url: 'https://loneboo-images.s3.eu-south-1.amazonaws.com/a17.webp', category: 'ANIMAL', label: 'Serpente' },
    { id: 'a18', url: 'https://loneboo-images.s3.eu-south-1.amazonaws.com/a18.webp', category: 'ANIMAL', label: 'Tartaruga' },
    { id: 'a19', url: 'https://loneboo-images.s3.eu-south-1.amazonaws.com/a19.webp', category: 'ANIMAL', label: 'Tigre' },
    { id: 'a20', url: 'https://loneboo-images.s3.eu-south-1.amazonaws.com/a20.webp', category: 'ANIMAL', label: 'Volpe' },
    { id: 'a21', url: 'https://loneboo-images.s3.eu-south-1.amazonaws.com/a21.webp', category: 'ANIMAL', label: 'Zebra' },
    { id: 'a22', url: 'https://loneboo-images.s3.eu-south-1.amazonaws.com/a22.webp', category: 'ANIMAL', label: 'Ape' },
    { id: 'a23', url: 'https://loneboo-images.s3.eu-south-1.amazonaws.com/a23.webp', category: 'ANIMAL', label: 'Cammello' },
    { id: 'a24', url: 'https://loneboo-images.s3.eu-south-1.amazonaws.com/a24.webp', category: 'ANIMAL', label: 'Coniglio' },
    { id: 'a25', url: 'https://loneboo-images.s3.eu-south-1.amazonaws.com/a25.webp', category: 'ANIMAL', label: 'Gatto' }
];