
import { QuizQuestion } from '../types';

/**
 * DATABASE DELLE DOMANDE - LONE BOO QUIZ
 * Formato: id, question, options (array di 4 stringhe), correctAnswer (indice 0, 1, 2 o 3).
 */

export const QUIZ_EASY: QuizQuestion[] = [
    { id: 1, question: "Di che colore è il cielo di giorno?", options: ["Verde", "Blu", "Viola", "Nero"], correctAnswer: 1 },
    { id: 2, question: "Quanti zampe ha un cane?", options: ["4", "2", "6", "10"], correctAnswer: 0 },
    { id: 3, question: "Quale frutto è giallo e lungo?", options: ["Banana", "Mela", "Fragola", "Ciliegia"], correctAnswer: 0 },
    { id: 4, question: "Dove vive il pesce?", options: ["Sulla terra", "Nell’acqua", "Nel cielo", "Sulla luna"], correctAnswer: 1 },
    { id: 5, question: "Quale animale fa “muu”?", options: ["Mucca", "Cane", "Gatto", "Uccellino"], correctAnswer: 0 },
    { id: 6, question: "Che forma ha una palla?", options: ["Quadrata", "Rotonda", "Triangolare", "A stella"], correctAnswer: 1 },
    { id: 7, question: "Quante ore ci sono in un giorno?", options: ["24", "12", "48", "100"], correctAnswer: 0 },
    { id: 8, question: "Quale colore ottieni mescolando rosso e blu?", options: ["Viola", "Verde", "Arancione", "Rosa"], correctAnswer: 0 },
    { id: 9, question: "Che cosa usi per scrivere su un foglio?", options: ["Forchetta", "Matita", "Cucchiaio", "Pettine"], correctAnswer: 1 },
    { id: 10, question: "Quale animale vola nel cielo?", options: ["Elefante", "Uccello", "Cavallo", "Pesce"], correctAnswer: 1 },
    { id: 11, question: "Di che colore è il sole?", options: ["Giallo", "Nero", "Blu", "Marrone"], correctAnswer: 0 },
    { id: 12, question: "Che suono fa un gatto?", options: ["Miao", "Bau", "Cip", "Grugn"], correctAnswer: 0 },
    { id: 13, question: "Dove crescono le mele?", options: ["Sulla terra", "Sugli alberi", "Nel mare", "Nelle scarpe"], correctAnswer: 1 },
    { id: 14, question: "Quanti giorni ci sono in una settimana?", options: ["5", "7", "10", "3"], correctAnswer: 1 },
    { id: 15, question: "Quale animale ha la proboscide?", options: ["Elefante", "Coniglio", "Cane", "Formica"], correctAnswer: 0 },
    { id: 16, question: "Cosa indossi ai piedi?", options: ["Cappello", "Scarpe", "Guanti", "Occhiali"], correctAnswer: 1 },
    { id: 17, question: "Quale frutto è rosso e piccolo?", options: ["Fragola", "Banana", "Pera", "Ananas"], correctAnswer: 0 },
    { id: 18, question: "Che colore ha la neve?", options: ["Bianca", "Verde", "Rosa", "Blu"], correctAnswer: 0 },
    { id: 19, question: "Come si chiama il periodo di riposo dei bambini di notte?", options: ["Colazione", "Sonno", "Gioco", "Sport"], correctAnswer: 1 },
    { id: 20, question: "Quale animale dice “bau bau”?", options: ["Cane", "Gatto", "Mucca", "Leone"], correctAnswer: 0 },
    { id: 21, question: "Qual è il numero dopo il 7?", options: ["8", "6", "10", "1"], correctAnswer: 0 },
    { id: 22, question: "Dove vivono i pinguini?", options: ["Deserto", "Polo Sud", "Foresta", "Cucina"], correctAnswer: 1 },
    { id: 23, question: "Quale animale fa le uova?", options: ["Gatto", "Gallina", "Leone", "Cane"], correctAnswer: 1 },
    { id: 24, question: "Di che colore è un limone?", options: ["Giallo", "Rosso", "Blu", "Nero"], correctAnswer: 0 },
    { id: 25, question: "Quale oggetto usi per lavarti i denti?", options: ["Spazzolino", "Pettine", "Forchetta", "Penna"], correctAnswer: 0 },
    { id: 26, question: "Che animale è grande e grigio con la proboscide?", options: ["Elefante", "Cavallo", "Coniglio", "Gatto"], correctAnswer: 0 },
    { id: 27, question: "Quale stagione viene dopo l’inverno?", options: ["Primavera", "Estate", "Autunno", "Natale"], correctAnswer: 0 },
    { id: 28, question: "Quale animale salta e fa “cra cra”?", options: ["Rana", "Cane", "Gatto", "Gallo"], correctAnswer: 0 },
    { id: 29, question: "Quale frutto è arancione e rotondo?", options: ["Arancia", "Mela", "Fragola", "Limone"], correctAnswer: 0 },
    { id: 30, question: "Quanti colori ci sono nell’arcobaleno?", options: ["7", "5", "3", "100"], correctAnswer: 0 },
    { id: 31, question: "Che animale ha la coda lunga e miagola?", options: ["Gatto", "Cane", "Mucca", "Topolino"], correctAnswer: 0 },
    { id: 32, question: "Quale mezzo va sull’acqua?", options: ["Barca", "Auto", "Treno", "Aereo"], correctAnswer: 0 },
    { id: 33, question: "Che animale ha le ali e canta al mattino?", options: ["Uccello", "Pesce", "Cane", "Maiale"], correctAnswer: 0 },
    { id: 34, question: "Quale colore ha una carota?", options: ["Arancione", "Blu", "Viola", "Rosa"], correctAnswer: 0 },
    { id: 35, question: "Quanti giorni ha febbraio (in un anno normale)?", options: ["28", "30", "31", "10"], correctAnswer: 0 },
    { id: 36, question: "Quale animale fa “hihi” e salta in giro?", options: ["Cavallo", "Gallo", "Pecora", "Pesce"], correctAnswer: 0 },
    { id: 37, question: "Dove cresce il mais?", options: ["Albero", "Campo", "Mare", "Frigorifero"], correctAnswer: 1 },
    { id: 38, question: "Quale frutto è verde fuori e rosso dentro?", options: ["Anguria", "Banana", "Pera", "Mela"], correctAnswer: 0 },
    { id: 39, question: "Cosa usi per colorare?", options: ["Pastelli", "Forchetta", "Pennello per dipingere", "Martello"], correctAnswer: 0 },
    { id: 40, question: "Quale animale ha le strisce bianche e nere?", options: ["Zebra", "Elefante", "Leone", "Maiale"], correctAnswer: 0 },
    { id: 41, question: "Che animale dice “cip cip”?", options: ["Uccellino", "Cane", "Gatto", "Mucca"], correctAnswer: 0 },
    { id: 42, question: "Dove vive un orso polare?", options: ["Polo Nord", "Deserto", "Foresta tropicale", "Città"], correctAnswer: 0 },
    { id: 43, question: "Quante ali ha una farfalla?", options: ["2", "4", "6", "Nessuna"], correctAnswer: 1 },
    { id: 44, question: "Quale frutto è dolce e rosso dentro?", options: ["Ciliegia", "Limone", "Kiwi", "Banana"], correctAnswer: 0 },
    { id: 45, question: "Quale animale ha una lunga criniera e fa “hiiiii”?", options: ["Cavallo", "Mucca", "Cane", "Pecora"], correctAnswer: 0 },
    { id: 46, question: "Che animale porta il miele?", options: ["Ape", "Elefante", "Pesce", "Gatto"], correctAnswer: 0 },
    { id: 47, question: "Quale colore ha il fuoco?", options: ["Rosso / arancione", "Blu", "Verde", "Viola"], correctAnswer: 0 },
    { id: 48, question: "Cosa bevi a colazione spesso?", options: ["Latte", "Benzina", "Olio", "Vernice"], correctAnswer: 0 },
    { id: 49, question: "Che animale ha una conchiglia?", options: ["Lumaca", "Cane", "Uccello", "Leone"], correctAnswer: 0 },
    { id: 50, question: "Quale animale vive in una tana e ha le orecchie lunghe?", options: ["Coniglio", "Gatto", "Leone", "Pecora"], correctAnswer: 0 },
    { id: 51, question: "Quale animale ha la criniera e ruggisce?", options: ["Leone", "Pecora", "Gatto", "Gallo"], correctAnswer: 0 },
    { id: 52, question: "Dove cresce il grano?", options: ["Campo", "Albero", "Mare", "Cielo"], correctAnswer: 0 },
    { id: 53, question: "Quale frutto è piccolo, blu e dolce?", options: ["Mirtillo", "Banana", "Arancia", "Limone"], correctAnswer: 0 },
    { id: 54, question: "Che animale fa “grugn grugn”?", options: ["Maiale", "Gatto", "Cane", "Uccellino"], correctAnswer: 0 },
    { id: 55, question: "Quale mezzo vola nel cielo?", options: ["Aereo", "Barca", "Auto", "Treno"], correctAnswer: 0 },
    { id: 56, question: "Quale animale ha le macchie nere sul corpo bianco?", options: ["Mucca", "Cane", "Gatto", "Leone"], correctAnswer: 0 },
    { id: 57, question: "Che colore ha un pomodoro maturo?", options: ["Rosso", "Verde", "Blu", "Viola"], correctAnswer: 0 },
    { id: 58, question: "Quanti minuti ci sono in un’ora?", options: ["60", "30", "100", "10"], correctAnswer: 0 },
    { id: 59, question: "Quale animale fa “coccodecò”?", options: ["Gallo", "Cane", "Cavallo", "Gatto"], correctAnswer: 0 },
    { id: 60, question: "Dove vive un pesce pagliaccio?", options: ["Mare", "Cielo", "Bosco", "Deserto"], correctAnswer: 0 },
    { id: 61, question: "Che animale è piccolo, ha le ali e fa “bzz”?", options: ["Ape", "Cavallo", "Gatto", "Elefante"], correctAnswer: 0 },
    { id: 62, question: "Quale frutto è giallo e dolce dentro?", options: ["Banana", "Mela", "Fragola", "Uva"], correctAnswer: 0 },
    { id: 63, question: "Quale animale fa “chioccia” e porta le uova?", options: ["Gallina", "Cane", "Coniglio", "Maiale"], correctAnswer: 0 },
    { id: 64, question: "Che animale vive nelle foreste e ha la coda folta?", options: ["Volpe", "Pesce", "Gallo", "Mucca"], correctAnswer: 0 },
    { id: 65, question: "Quale mezzo va sui binari?", options: ["Treno", "Barca", "Aereo", "Bici"], correctAnswer: 0 },
    { id: 66, question: "Quale colore ha un girasole?", options: ["Giallo", "Blu", "Rosso", "Viola"], correctAnswer: 0 },
    { id: 67, question: "Quante ruote ha una bicicletta?", options: ["2", "4", "3", "1"], correctAnswer: 0 },
    { id: 68, question: "Che animale vive nella savana e ha il collo lungo?", options: ["Giraffa", "Leone", "Cavallo", "Maiale"], correctAnswer: 0 },
    { id: 69, question: "Quale animale salta tanto e fa “cra cra”?", options: ["Rana", "Cane", "Gatto", "Gallo"], correctAnswer: 0 },
    { id: 70, question: "Dove cresce un cactus?", options: ["Deserto", "Mare", "Bosco", "Cielo"], correctAnswer: 0 },
    { id: 71, question: "Quale frutto è rosso fuori e rosso dentro?", options: ["Ciliegia", "Banana", "Kiwi", "Mela"], correctAnswer: 0 },
    { id: 72, question: "Che animale ha le strisce nere e arancioni?", options: ["Tigre", "Zebra", "Cavallo", "Maiale"], correctAnswer: 0 },
    { id: 73, question: "Dove cresce la fragola?", options: ["Pianta bassa", "Albero", "Mare", "Sottoterra"], correctAnswer: 0 },
    { id: 74, question: "Quale animale vive nell’acqua e ha le pinne?", options: ["Pesce", "Cane", "Gatto", "Uccello"], correctAnswer: 0 },
    { id: 75, question: "Che animale ha le corna e fa “beee”?", options: ["Pecora", "Cavallo", "Cane", "Maiale"], correctAnswer: 0 },
    { id: 76, question: "Quale frutto è verde fuori e verde dentro?", options: ["Kiwi", "Banana", "Mela", "Fragola"], correctAnswer: 0 },
    { id: 77, question: "Quale animale fa “cu-cu”?", options: ["Gufo", "Cane", "Gatto", "Elefante"], correctAnswer: 0 },
    { id: 78, question: "Che colore ha l’erba?", options: ["Verde", "Blu", "Rosso", "Giallo"], correctAnswer: 0 },
    { id: 79, question: "Quale animale vive nelle case e fa “miao”?", options: ["Gatto", "Cane", "Mucca", "Giraffa"], correctAnswer: 0 },
    { id: 80, question: "Quale frutto è dolce e arancione dentro?", options: ["Albicocca", "Limone", "Kiwi", "Mela"], correctAnswer: 0 },
    { id: 81, question: "Che animale ha la coda a ricciolo e fa “oink oink”?", options: ["Maiale", "Cane", "Cavallo", "Gatto"], correctAnswer: 0 },
    { id: 82, question: "Quale mezzo va sull’acqua?", options: ["Barca", "Bicicletta", "Auto", "Treno"], correctAnswer: 0 },
    { id: 83, question: "Che animale ha la criniera e corre veloce?", options: ["Cavallo", "Cane", "Gatto", "Elefante"], correctAnswer: 0 },
    { id: 84, question: "Quale frutto è rosso fuori e bianco dentro con semi neri?", options: ["Fragola", "Banana", "Mela", "Pera"], correctAnswer: 0 },
    { id: 85, question: "Dove vive il cammello?", options: ["Deserto", "Bosco", "Mare", "Città"], correctAnswer: 0 },
    { id: 86, question: "Che animale ha le ali e non può volare?", options: ["Struzzo", "Gatto", "Pesce", "Ape"], correctAnswer: 0 },
    { id: 87, question: "Quale colore ha il cielo al tramonto?", options: ["Arancione / rosa", "Verde", "Blu scuro", "Nero"], correctAnswer: 0 },
    { id: 88, question: "Quale animale fa “hihihi” e salta?", options: ["Cavallo", "Gallo", "Cane", "Mucca"], correctAnswer: 0 },
    { id: 89, question: "Dove vive la tartaruga?", options: ["Terra e acqua", "Cielo", "Bosco", "Deserto"], correctAnswer: 0 },
    { id: 90, question: "Quale frutto è viola e piccolo?", options: ["Uva", "Mela", "Banana", "Pera"], correctAnswer: 0 },
    { id: 91, question: "Che animale porta le api nel favo?", options: ["Ape", "Coniglio", "Cane", "Leone"], correctAnswer: 0 },
    { id: 92, question: "Quale animale vive nel Polo Nord e nuota nell’acqua fredda?", options: ["Orso polare", "Leone", "Tigre", "Giraffa"], correctAnswer: 0 },
    { id: 93, question: "Quante ali ha un’ape?", options: ["4", "2", "6", "Nessuna"], correctAnswer: 0 },
    { id: 94, question: "Che animale ha le macchie e vive in Africa?", options: ["Giraffa", "Cane", "Cavallo", "Maiale"], correctAnswer: 0 },
    { id: 95, question: "Quale mezzo vola sopra le mountains?", options: ["Aereo", "Barca", "Auto", "Treno"], correctAnswer: 0 },
    { id: 96, question: "Che animale fa “oink oink”?", options: ["Maiale", "Cane", "Gatto", "Gallo"], correctAnswer: 0 },
    { id: 97, question: "Quale frutto è rosso e tondo?", options: ["Mela", "Banana", "Kiwi", "Ananas"], correctAnswer: 0 },
    { id: 98, question: "Dove vive un coniglio?", options: ["Tana", "Albero", "Mare", "Cielo"], correctAnswer: 0 },
    { id: 99, question: "Quale animale ha la coda lunga e fa “ciao ciao”?", options: ["Scimmia", "Cane", "Gatto", "Maiale"], correctAnswer: 0 },
    { id: 100, question: "Che animale vive in mare e ha le pinne?", options: ["Pesce", "Cavallo", "Cane", "Mucca"], correctAnswer: 0 },
];

export const QUIZ_MEDIUM: QuizQuestion[] = [
    { id: 101, question: "Qual è la capitale d’Italia?", options: ["Roma", "Milano", "Napoli", "Venezia"], correctAnswer: 0 },
    { id: 102, question: "Chi ha scritto “Pinocchio”?", options: ["Carlo Collodi", "Gianni Rodari", "Italo Calvino", "Dante"], correctAnswer: 0 },
    { id: 103, question: "Cosa indica un semaforo rosso?", options: ["Stop", "Vai", "Attenzione", "Accelera"], correctAnswer: 0 },
    { id: 104, question: "Qual è il simbolo della pace?", options: ["Colomba", "Leone", "Sole", "Luna"], correctAnswer: 0 },
    { id: 105, question: "Quale organo serve a pompare il sangue?", options: ["Cuore", "Polmone", "Fegato", "Stomaco"], correctAnswer: 0 },
    { id: 106, question: "Quale continente si trova a sud dell’Europa?", options: ["Africa", "Asia", "Oceania", "America"], correctAnswer: 0 },
    { id: 107, question: "Cosa si deve fare prima di attraversare la strada?", options: ["Guardare a destra e sinistra", "Correre", "Chiudere gli occhi", "Saltare"], correctAnswer: 0 },
    { id: 108, question: "Quale animale è famoso per costruire dighe?", options: ["Castoro", "Lupo", "Gatto", "Cane"], correctAnswer: 0 },
    { id: 109, question: "Quale pianeta è il più vicino al Sole?", options: ["Mercurio", "Marte", "Giove", "Terra"], correctAnswer: 0 },
    { id: 110, question: "Cosa significa riciclare?", options: ["Riutilizzare materiali", "Buttare tutto", "Comprarne di nuovi", "Dimenticare"], correctAnswer: 0 },
    { id: 111, question: "Chi è il Presidente della Repubblica italiana?", options: ["Sergio Mattarella", "Mario Draghi", "Giuseppe Conte", "Lone Boo"], correctAnswer: 0 },
    { id: 112, question: "Come si chiama la linea che separa i due emisferi della Terra?", options: ["Equatore", "Meridiano", "Tropico del Cancro", "Confine"], correctAnswer: 0 },
    { id: 113, question: "Qual è l’unità di misura della lunghezza nel Sistema Internazionale?", options: ["Metro", "Litro", "Chilogrammo", "Secondo"], correctAnswer: 0 },
    { id: 114, question: "Quale pianeta è noto come il Pianeta Rosso?", options: ["Marte", "Venere", "Saturno", "Plutone"], correctAnswer: 0 },
    { id: 115, question: "Cosa bisogna fare se vediamo qualcuno ferito?", options: ["Chiamare aiuto", "Ignorarlo", "Correre via", "Scattare una foto"], correctAnswer: 0 },
    { id: 116, question: "Quale tra questi strumenti serve per ascoltare la musica?", options: ["Cuffie", "Forbici", "Righello", "Martello"], correctAnswer: 0 },
    { id: 117, question: "Chi ha inventato il telefono?", options: ["Alexander Graham Bell", "Thomas Edison", "Galileo Galilei", "Leonardo"], correctAnswer: 0 },
    { id: 118, question: "Qual è il numero massimo di giocatori in una squadra di calcio?", options: ["11", "7", "5", "20"], correctAnswer: 0 },
    { id: 119, question: "Cosa è una democrazia?", options: ["Un sistema in cui i cittadini votano", "Una scuola", "Una gara di corsa", "Un animale"], correctAnswer: 0 },
    { id: 120, question: "Quale gas respiriamo per vivere?", options: ["Ossigeno", "Azoto", "Anidride carbonica", "Elio"], correctAnswer: 0 },
    { id: 121, question: "Come si chiama il famoso monumento di Parigi?", options: ["Torre Eiffel", "Colosseo", "Big Ben", "Piramide"], correctAnswer: 0 },
    { id: 122, question: "Quale animale produce il miele?", options: ["Ape", "Cavallo", "Cane", "Formica"], correctAnswer: 0 },
    { id: 123, question: "Cosa si mette in una lavastoviglie?", options: ["Piatti e posate", "Vestiti", "Libri", "Scarpe"], correctAnswer: 0 },
    { id: 124, question: "Chi ha scritto “Favole al telefono”?", options: ["Gianni Rodari", "Italo Calvino", "Alessandro Manzoni", "Petrarca"], correctAnswer: 0 },
    { id: 125, question: "Qual è la materia in cui si studiano numeri e calcoli?", options: ["Matematica", "Storia", "Geografia", "Sport"], correctAnswer: 0 },
    { id: 126, question: "Cos’è un referendum?", options: ["Un voto dei cittadini", "Un tipo di festa", "Un animale", "Un cibo"], correctAnswer: 0 },
    { id: 127, question: "Quale pianeta ha gli anelli?", options: ["Saturno", "Marte", "Mercurio", "Venere"], correctAnswer: 0 },
    { id: 128, question: "Chi aiuta a mantenere l’ordine in città?", options: ["Polizia", "Dottore", "Insegnante", "Postino"], correctAnswer: 0 },
    { id: 129, question: "Qual è il simbolo chimico dell’acqua?", options: ["H₂O", "CO₂", "O₂", "NaCl"], correctAnswer: 0 },
    { id: 130, question: "Cosa indica un triangolo con un punto esclamativo sulle strade?", options: ["Pericolo", "Parcheggio", "Divieto", "Benzina"], correctAnswer: 0 },
    { id: 131, question: "Quale continente è il più grande per superficie?", options: ["Asia", "Africa", "Europa", "Oceania"], correctAnswer: 0 },
    { id: 132, question: "Chi ha scritto “I Promessi Sposi”?", options: ["Alessandro Manzoni", "Dante Alighieri", "Luigi Pirandello", "Collodi"], correctAnswer: 0 },
    { id: 133, question: "Cosa significa “cittadinanza attiva”?", options: ["Partecipare alla vita della comunità", "Andare a scuola", "Dormire", "Giocare"], correctAnswer: 0 },
    { id: 134, question: "Quale strumento si usa per disegnare cerchi?", options: ["Compasso", "Righello", "Pennarello", "Gomma"], correctAnswer: 0 },
    { id: 135, question: "Quale pianeta è famoso per la sua grande macchia rossa?", options: ["Giove", "Marte", "Saturno", "Terra"], correctAnswer: 0 },
    { id: 136, question: "Cos’è una carta d’identità?", options: ["Documento di riconoscimento", "Un gioco", "Una moneta", "Un libro"], correctAnswer: 0 },
    { id: 137, question: "Che cosa studia la geografia?", options: ["Terra e luoghi", "Animali", "Numeri", "Stelle"], correctAnswer: 0 },
    { id: 138, question: "Cosa si festeggia il 2 giugno in Italia?", options: ["Festa della Repubblica", "Natale", "Pasqua", "Compleanno"], correctAnswer: 0 },
    { id: 139, question: "Quale mezzo serve a viaggiare in acqua?", options: ["Barca", "Bicicletta", "Auto", "Moto"], correctAnswer: 0 },
    { id: 140, question: "Chi ha dipinto la Gioconda?", options: ["Leonardo da Vinci", "Michelangelo", "Raffaello", "Picasso"], correctAnswer: 0 },
    { id: 141, question: "Cosa si deve fare per proteggere l’ambiente?", options: ["Riciclare e non sprecare", "Comprare sempre nuovo", "Buttare tutto", "Usare plastica"], correctAnswer: 0 },
    { id: 142, question: "Quale materia si studia per conoscere i fatti del passato?", options: ["Storia", "Scienze", "Italiano", "Musica"], correctAnswer: 0 },
    { id: 143, question: "Cos’è un abuso?", options: ["Un comportamento ingiusto verso altri", "Una festa", "Un gioco", "Un dolce"], correctAnswer: 0 },
    { id: 144, question: "Quale frutto cresce sugli alberi e può essere rosso, verde o giallo?", options: ["Mela", "Banana", "Fragola", "Uva"], correctAnswer: 0 },
    { id: 145, question: "Qual è l’animale più grande del mondo?", options: ["Balena azzurra", "Elefante", "Giraffa", "Dinosauro"], correctAnswer: 0 },
    { id: 146, question: "Che cosa si trova in una biblioteca?", options: ["Libri", "Auto", "Cibi", "Vestiti"], correctAnswer: 0 },
    { id: 147, question: "Quale pianeta è più grande della Terra?", options: ["Giove", "Marte", "Venere", "Plutone"], correctAnswer: 0 },
    { id: 148, question: "Cosa significa “rispettare le regole”?", options: ["Comportarsi correttamente", "Fare quello che si vuole", "Ignorare gli altri", "Urlare"], correctAnswer: 0 },
    { id: 149, question: "Quale strumento serve per misurare la temperatura?", options: ["Termometro", "Righello", "Bussola", "Orologio"], correctAnswer: 0 },
    { id: 150, question: "Chi protegge i diritti dei cittadini?", options: ["Legge e tribunali", "Medico", "Postino", "Vigile"], correctAnswer: 0 },
    { id: 151, question: "Chi canta la canzone “Shape of You”?", options: ["Ed Sheeran", "Justin Bieber", "Shawn Mendes", "Zuccotto"], correctAnswer: 0 },
    { id: 152, question: "Quale strumento ha corde e si suona pizzicandole?", options: ["Chitarra", "Batteria", "Flauto", "Tromba"], correctAnswer: 0 },
    { id: 153, question: "Chi è il protagonista di “Harry Potter”?", options: ["Harry Potter", "Ron Weasley", "Draco Malfoy", "Batman"], correctAnswer: 0 },
    { id: 154, question: "In quale film appare Elsa?", options: ["Frozen", "Moana", "Rapunzel", "Cenerentola"], correctAnswer: 0 },
    { id: 155, question: "Quale strumento ha 88 tasti?", options: ["Pianoforte", "Violino", "Batteria", "Xilofono"], correctAnswer: 0 },
    { id: 156, question: "Chi è Spider-Man?", options: ["Peter Parker", "Bruce Wayne", "Clark Kent", "Uomo Invisibile"], correctAnswer: 0 },
    { id: 157, question: "Quale cantante è famosa per “Bad Romance”?", options: ["Lady Gaga", "Beyoncé", "Ariana Grande", "Katy Perry"], correctAnswer: 0 },
    { id: 158, question: "Quale personaggio dice “Hakuna Matata”?", options: ["Timon e Pumbaa", "Simba", "Scar", "Mufasa"], correctAnswer: 0 },
    { id: 159, question: "Quale sport usa una palla rotonda da calciare?", options: ["Calcio", "Basket", "Tennis", "Rugby"], correctAnswer: 0 },
    { id: 160, question: "Quale strumento si suona con le bacchette?", options: ["Batteria", "Violino", "Pianoforte", "Chitarra"], correctAnswer: 0 },
    { id: 161, question: "Chi è il supereroe con un martello?", options: ["Thor", "Iron Man", "Captain America", "Hulk"], correctAnswer: 0 },
    { id: 162, question: "Quale cantante è conosciuto come “Re del Pop”?", options: ["Michael Jackson", "Justin Timberlake", "Bruno Mars", "Elvis"], correctAnswer: 0 },
    { id: 163, question: "In quale film trovi il personaggio Olaf?", options: ["Frozen", "Cattivissimo Me", "Shrek", "Nemo"], correctAnswer: 0 },
    { id: 164, question: "Quale strumento ha fiato e tasti, si usa in orchestre?", options: ["Flauto", "Chitarra", "Batteria", "Violino"], correctAnswer: 0 },
    { id: 165, question: "Chi canta “Let It Go”?", options: ["Idina Menzel", "Demi Lovato", "Taylor Swift", "Elsa"], correctAnswer: 0 },
    { id: 166, question: "Quale personaggio ha il mantello rosso e vola nel cielo?", options: ["Superman", "Batman", "Spiderman", "Robin"], correctAnswer: 0 },
    { id: 167, question: "In quale film trovi il mostro Mike Wazowski?", options: ["Monsters & Co.", "Toy Story", "Alla ricerca di Nemo", "Frozen"], correctAnswer: 0 },
    { id: 168, question: "Quale sport si gioca con racchette e volano?", options: ["Badminton", "Basket", "Calcio", "Volley"], correctAnswer: 0 },
    { id: 169, question: "Quale cantante ha scritto “Shake It Off”?", options: ["Taylor Swift", "Selena Gomez", "Billie Eilish", "Madonna"], correctAnswer: 0 },
    { id: 170, question: "Quale supereroe indossa un costume nero e ha artigli?", options: ["Black Panther", "Spider-Man", "Thor", "Wolverine"], correctAnswer: 0 },
    { id: 171, question: "In quale film trovi la città di Agrabah?", options: ["Aladdin", "Frozen", "Mulan", "Cenerentola"], correctAnswer: 0 },
    { id: 172, question: "Quale strumento ha corde ed è piccolo, simile a un violino?", options: ["Ukulele", "Chitarra", "Pianoforte", "Arpa"], correctAnswer: 0 },
    { id: 173, question: "Chi canta “Happy”?", options: ["Pharrell Williams", "Justin Bieber", "Bruno Mars", "Coldplay"], correctAnswer: 0 },
    { id: 174, question: "Quale personaggio è il re della giungla?", options: ["Simba", "Scar", "Timon", "Mufasa"], correctAnswer: 0 },
    { id: 175, question: "Quale sport usa una palla e un canestro?", options: ["Basket", "Tennis", "Calcio", "Golf"], correctAnswer: 0 },
    { id: 176, question: "Quale film parla di una fattoria di animali parlanti?", options: ["Zootropolis", "Madagascar", "Shrek", "Nemo"], correctAnswer: 0 },
    { id: 177, question: "Chi canta “Uptown Funk”?", options: ["Bruno Mars", "Ed Sheeran", "Justin Bieber", "Dua Lipa"], correctAnswer: 0 },
    { id: 178, question: "In quale film trovi Woody e Buzz?", options: ["Toy Story", "Frozen", "Minions", "Shrek"], correctAnswer: 0 },
    { id: 179, question: "Quale strumento ha 6 corde?", options: ["Chitarra", "Violino", "Pianoforte", "Tromba"], correctAnswer: 0 },
    { id: 180, question: "Chi è l’amico verde di Shrek?", options: ["Ciuchino", "Orco", "Lord Farquaad", "Gatto"], correctAnswer: 1 },
    { id: 181, question: "Quale cantante è famoso per “Bad Guy”?", options: ["Billie Eilish", "Ariana Grande", "Taylor Swift", "Dua Lipa"], correctAnswer: 0 },
    { id: 182, question: "Quale supereroe ha un martello che solo lui può sollevare?", options: ["Thor", "Iron Man", "Hulk", "Captain America"], correctAnswer: 0 },
    { id: 183, question: "In quale film trovi il personaggio Elsa?", options: ["Frozen", "Moana", "Rapunzel", "Mulan"], correctAnswer: 0 },
    { id: 184, question: "Quale sport si gioca con un disco di ghiaccio?", options: ["Hockey", "Basket", "Calcio", "Sci"], correctAnswer: 0 },
    { id: 185, question: "Quale strumento si suona pizzicando le corde?", options: ["Chitarra", "Tromba", "Batteria", "Flauto"], correctAnswer: 0 },
    { id: 186, question: "Chi canta “Rolling in the Deep”?", options: ["Adele", "Lady Gaga", "Ariana Grande", "Rihanna"], correctAnswer: 0 },
    { id: 187, question: "In quale film ci sono i Minions?", options: ["Cattivissimo Me", "Shrek", "Toy Story", "Nemo"], correctAnswer: 0 },
    { id: 188, question: "Quale personaggio ha il martello magico e capelli biondi?", options: ["Thor", "Hulk", "Iron Man", "Batman"], correctAnswer: 0 },
    { id: 189, question: "Quale cantante ha scritto “Sorry”?", options: ["Justin Bieber", "Shawn Mendes", "Ed Sheeran", "Drake"], correctAnswer: 0 },
    { id: 190, question: "In quale film trovi il pesce Nemo?", options: ["Alla ricerca di Nemo", "Shark Tale", "Oceania", "Frozen"], correctAnswer: 0 },
    { id: 191, question: "Quale strumento si suona con le mani e pelli tese?", options: ["Batteria", "Flauto", "Chitarra", "Pianoforte"], correctAnswer: 0 },
    { id: 192, question: "Chi canta “Firework”?", options: ["Katy Perry", "Taylor Swift", "Ariana Grande", "Beyoncé"], correctAnswer: 0 },
    { id: 193, question: "Quale supereroe indossa un costume rosso e blu?", options: ["Spider-Man", "Batman", "Superman", "Flash"], correctAnswer: 0 },
    { id: 194, question: "In quale film trovi la sirena Ariel?", options: ["La Sirenetta", "Frozen", "Moana", "Bambi"], correctAnswer: 0 },
    { id: 195, question: "Quale sport si gioca con la racchetta e la palla su un campo verde?", options: ["Tennis", "Basket", "Calcio", "Golf"], correctAnswer: 0 },
    { id: 196, question: "Chi canta “Shape of You”?", options: ["Ed Sheeran", "Shawn Mendes", "Justin Bieber", "Zayn"], correctAnswer: 0 },
    { id: 197, question: "Quale personaggio ha un amico piccolo e verde che dice “Io sono il vostro re”?", options: ["Yoda", "Shrek", "Hulk", "Batman"], correctAnswer: 0 },
    { id: 198, question: "Quale strumento fa “tromba tromba”?", options: ["Tromba", "Chitarra", "Batteria", "Violino"], correctAnswer: 0 },
    { id: 199, question: "In quale film trovi un regno ghiacciato chiamato Arendelle?", options: ["Frozen", "Aladdin", "Mulan", "Shrek"], correctAnswer: 0 },
    { id: 200, question: "Chi è il leader dei Minions?", options: ["Gru", "Kevin", "Stuart", "Bob"], correctAnswer: 0 },
];

export const QUIZ_HARD: QuizQuestion[] = [
    { id: 201, question: "Qual è la capitale della Francia?", options: ["Parigi", "Londra", "Berlino", "Madrid"], correctAnswer: 0 },
    { id: 202, question: "Chi ha scritto “Romeo e Giulietta”?", options: ["William Shakespeare", "Charles Dickens", "Victor Hugo", "Dante"], correctAnswer: 0 },
    { id: 203, question: "Quale pianeta è conosciuto come il “Pianeta Rosso”?", options: ["Marte", "Giove", "Venere", "Saturno"], correctAnswer: 0 },
    { id: 204, question: "Chi ha composto la “Nona Sinfonia”?", options: ["Beethoven", "Mozart", "Bach", "Vivaldi"], correctAnswer: 0 },
    { id: 205, question: "In quale film trovi il personaggio Joker?", options: ["Batman", "Spider-Man", "Superman", "Avengers"], correctAnswer: 0 },
    { id: 206, question: "Quale cantante è noto per l’album “1989”?", options: ["Taylor Swift", "Ariana Grande", "Billie Eilish", "Rihanna"], correctAnswer: 0 },
    { id: 207, question: "Qual è il fiume più lungo del mondo?", options: ["Nilo", "Mississippi", "Rio delle Amazzoni", "Po"], correctAnswer: 0 },
    { id: 208, question: "Chi ha scoperto la legge di gravitazione universale?", options: ["Isaac Newton", "Albert Einstein", "Galileo Galilei", "Darwin"], correctAnswer: 0 },
    { id: 209, question: "In quale film trovi il personaggio Tony Stark?", options: ["Iron Man", "Thor", "Captain America", "Spiderman"], correctAnswer: 0 },
    { id: 210, question: "Quale cantante ha inciso “Blinding Lights”?", options: ["The Weeknd", "Justin Bieber", "Ed Sheeran", "Drake"], correctAnswer: 0 },
    { id: 211, question: "Quale paese è famoso per i samurai e i sushi?", options: ["Giappone", "Cina", "Corea del Sud", "Thailandia"], correctAnswer: 0 },
    { id: 212, question: "Chi è l’autore della saga di “Harry Potter”?", options: ["J.K. Rowling", "Suzanne Collins", "Rick Riordan", "Tolkien"], correctAnswer: 0 },
    { id: 213, question: "Quale film ha vinto l’Oscar come miglior film nel 2020?", options: ["Parasite", "Joker", "1917", "Nomadland"], correctAnswer: 0 },
    { id: 214, question: "Quale cantante ha pubblicato l’album “Lover”?", options: ["Taylor Swift", "Billie Eilish", "Dua Lipa", "Madonna"], correctAnswer: 0 },
    { id: 215, question: "In quale sport si gioca con 11 giocatori per squadra e una palla ovale?", options: ["Rugby", "Basket", "Calcio", "Cricket"], correctAnswer: 0 },
    { id: 216, question: "Quale personaggio è noto come il “Capitano America”?", options: ["Steve Rogers", "Tony Stark", "Bruce Wayne", "Peter Parker"], correctAnswer: 0 },
    { id: 217, question: "Chi ha dipinto la “Gioconda”?", options: ["Leonardo da Vinci", "Michelangelo", "Raffaello", "Van Gogh"], correctAnswer: 0 },
    { id: 218, question: "Quale film racconta la vita di Elsa e Anna?", options: ["Frozen", "Rapunzel", "Oceania", "Brave"], correctAnswer: 0 },
    { id: 219, question: "Chi ha scritto “Il Piccolo Principe”?", options: ["Antoine de Saint-Exupéry", "J.K. Rowling", "Roald Dahl", "Collodi"], correctAnswer: 0 },
    { id: 220, question: "Quale cantante ha l’album “Divide”?", options: ["Ed Sheeran", "Shawn Mendes", "Justin Bieber", "Coldplay"], correctAnswer: 0 },
    { id: 221, question: "In quale sport si usano pedine e scacchiere?", options: ["Scacchi", "Dama", "Backgammon", "Sudoku"], correctAnswer: 0 },
    { id: 222, question: "Quale film è ambientato nel mondo dei videogiochi con Ralph?", options: ["Ralph Spaccatutto", "Wreck-It Ralph", "Tron", "Mario"], correctAnswer: 0 },
    { id: 223, question: "Chi ha scritto “1984”?", options: ["George Orwell", "Aldous Huxley", "Ray Bradbury", "Hemingway"], correctAnswer: 0 },
    { id: 224, question: "Quale cantante è noto per “Bad Guy”?", options: ["Billie Eilish", "Ariana Grande", "Dua Lipa", "Lorde"], correctAnswer: 0 },
    { id: 225, question: "In quale paese si trova la Torre Eiffel?", options: ["Francia", "Italia", "Germania", "USA"], correctAnswer: 0 },
    { id: 226, question: "Chi ha inventato la lampadina?", options: ["Thomas Edison", "Nikola Tesla", "Alexander Graham Bell", "Newton"], correctAnswer: 0 },
    { id: 227, question: "Quale film parla di una scuola di magia?", options: ["Harry Potter", "Percy Jackson", "Hunger Games", "Divergent"], correctAnswer: 0 },
    { id: 228, question: "Chi ha composto “Imagine”?", options: ["John Lennon", "Paul McCartney", "Elton John", "Freddie Mercury"], correctAnswer: 0 },
    { id: 229, question: "Quale sport si gioca su ghiaccio con disco e bastone?", options: ["Hockey su ghiaccio", "Curling", "Pattinaggio artistico", "Sci"], correctAnswer: 0 },
    { id: 230, question: "Chi è il regista di “Jurassic Park”?", options: ["Steven Spielberg", "James Cameron", "Christopher Nolan", "Lucas"], correctAnswer: 0 },
    { id: 231, question: "Quale cantante ha il brano “Levitating”?", options: ["Dua Lipa", "Ariana Grande", "Taylor Swift", "Halsey"], correctAnswer: 0 },
    { id: 232, question: "Quale fiume attraversa Londra?", options: ["Tamigi", "Senna", "Reno", "Tevere"], correctAnswer: 0 },
    { id: 233, question: "Chi ha scritto “Il Signore degli Anelli”?", options: ["J.R.R. Tolkien", "C.S. Lewis", "George R.R. Martin", "King"], correctAnswer: 0 },
    { id: 234, question: "In quale film trovi Elsa e Olaf?", options: ["Frozen", "Moana", "Rapunzel", "Encanto"], correctAnswer: 0 },
    { id: 235, question: "Chi ha teorizzato la relatività?", options: ["Albert Einstein", "Isaac Newton", "Galileo Galilei", "Bohr"], correctAnswer: 0 },
    { id: 236, question: "Quale cantante è noto per il brano “Sorry”?", options: ["Justin Bieber", "Shawn Mendes", "Ed Sheeran", "Niall Horan"], correctAnswer: 0 },
    { id: 237, question: "In quale sport si usa la racchetta per colpire un volano?", options: ["Badminton", "Tennis", "Ping-pong", "Squash"], correctAnswer: 0 },
    { id: 238, question: "Quale film ha come protagonista un supereroe con il mantello rosso?", options: ["Superman", "Batman", "Spider-Man", "Hulk"], correctAnswer: 0 },
    { id: 239, question: "Quale cantante ha pubblicato “Future Nostalgia”?", options: ["Dua Lipa", "Ariana Grande", "Billie Eilish", "Miley Cyrus"], correctAnswer: 0 },
    { id: 240, question: "Quale paese ha inventato la pizza?", options: ["Italia", "Grecia", "Spagna", "Turchia"], correctAnswer: 0 },
    { id: 241, question: "Chi è il personaggio principale di “Percy Jackson”?", options: ["Percy Jackson", "Harry Potter", "Katniss Everdeen", "Edward"], correctAnswer: 0 },
    { id: 242, question: "Quale film è ambientato a Wakanda?", options: ["Black Panther", "Avengers", "Spider-Man", "X-Men"], correctAnswer: 0 },
    { id: 243, question: "Chi ha scritto “Il Grande Gatsby”?", options: ["F. Scott Fitzgerald", "Ernest Hemingway", "Mark Twain", "Steinbeck"], correctAnswer: 0 },
    { id: 244, question: "Quale sport usa la palla ovale e touchdown?", options: ["Football americano", "Rugby", "Calcio", "Palla prigioniera"], correctAnswer: 0 },
    { id: 245, question: "Chi canta “Watermelon Sugar”?", options: ["Harry Styles", "Shawn Mendes", "Ed Sheeran", "Liam Payne"], correctAnswer: 0 },
    { id: 246, question: "In quale film trovi il personaggio Thanos?", options: ["Avengers", "Justice League", "Spider-Man", "Batman"], correctAnswer: 0 },
    { id: 247, question: "Chi ha composto la “5ª Sinfonia”?", options: ["Beethoven", "Mozart", "Chopin", "Schubert"], correctAnswer: 0 },
    { id: 248, question: "Quale cantante ha pubblicato l’album “Positions”?", options: ["Ariana Grande", "Dua Lipa", "Billie Eilish", "Katy Perry"], correctAnswer: 0 },
    { id: 249, question: "Quale paese ha il deserto del Sahara?", options: ["Algeria", "Egitto", "Libia", "Tutti questi"], correctAnswer: 3 },
    { id: 250, question: "Chi ha creato il personaggio di Batman?", options: ["Bob Kane", "Stan Lee", "Jack Kirby", "Ditko"], correctAnswer: 0 },
    { id: 251, question: "Qual è il fiume più lungo d’Italia?", options: ["Po", "Tevere", "Arno", "Adige"], correctAnswer: 0 },
    { id: 252, question: "Chi ha scritto “La Divina Commedia”?", options: ["Dante Alighieri", "Petrarca", "Boccaccio", "Leopardi"], correctAnswer: 0 },
    { id: 253, question: "Quale gas respiriamo principalmente?", options: ["Azoto", "Ossigeno", "Anidride carbonica", "Idrogeno"], correctAnswer: 0 },
    { id: 254, question: "Chi ha inventato il telefono?", options: ["Alexander Graham Bell", "Thomas Edison", "Nikola Tesla", "Meucci"], correctAnswer: 0 },
    { id: 255, question: "In quale città si trova il Colosseo?", options: ["Roma", "Napoli", "Firenze", "Milano"], correctAnswer: 0 },
    { id: 256, question: "Chi ha dipinto il soffitto della Cappella Sistina?", options: ["Michelangelo", "Leonardo da Vinci", "Raffaello", "Donatello"], correctAnswer: 0 },
    { id: 257, question: "Qual è il continente più grande per superficie?", options: ["Asia", "Africa", "America", "Antartide"], correctAnswer: 0 },
    { id: 258, question: "Chi ha scoperto l’America nel 1492?", options: ["Cristoforo Colombo", "Marco Polo", "Vasco da Gama", "Magellano"], correctAnswer: 0 },
    { id: 259, question: "Quale pianeta ha gli anelli più famosi?", options: ["Saturno", "Giove", "Urano", "Nettuno"], correctAnswer: 0 },
    { id: 260, question: "Chi è considerato il padre della psicoanalisi?", options: ["Sigmund Freud", "Carl Jung", "Alfred Adler", "Piaget"], correctAnswer: 0 },
    { id: 261, question: "Qual è l’animale più veloce sulla terra?", options: ["Ghepardo", "Leone", "Tigre", "Cavallo"], correctAnswer: 0 },
    { id: 262, question: "Quale lingua si parla in Brasile?", options: ["Portoghese", "Spagnolo", "Inglese", "Italiano"], correctAnswer: 0 },
    { id: 263, question: "Chi ha scritto “I Promessi Sposi”?", options: ["Alessandro Manzoni", "Giovanni Verga", "Italo Calvino", "Pirandello"], correctAnswer: 0 },
    { id: 264, question: "Qual è il pianeta più vicino al Sole?", options: ["Mercurio", "Venere", "Marte", "Terra"], correctAnswer: 0 },
    { id: 265, question: "Quale metallo ha simbolo chimico Fe?", options: ["Ferro", "Oro", "Argento", "Rame"], correctAnswer: 0 },
    { id: 266, question: "Chi ha inventato la stampa a caratteri mobili?", options: ["Johannes Gutenberg", "Leonardo da Vinci", "Galileo Galilei", "Edison"], correctAnswer: 0 },
    { id: 267, question: "In quale città si trova la Tour Eiffel?", options: ["Parigi", "Londra", "Berlino", "Lione"], correctAnswer: 0 },
    { id: 268, question: "Qual è il numero di pianeti del sistema solare?", options: ["8", "9", "7", "6"], correctAnswer: 0 },
    { id: 269, question: "Chi ha scritto “Il Principe”?", options: ["Niccolò Machiavelli", "Leonardo da Vinci", "Galileo Galilei", "Ariosto"], correctAnswer: 0 },
    { id: 270, question: "Quale stato ha per capitale Canberra?", options: ["Australia", "Nuova Zelanda", "Canada", "Brasile"], correctAnswer: 0 },
    { id: 271, question: "Quale elemento chimico ha simbolo O?", options: ["Ossigeno", "Oro", "Osmio", "Olio"], correctAnswer: 0 },
    { id: 272, question: "Chi ha composto “Il Flauto Magico”?", options: ["Mozart", "Beethoven", "Bach", "Wagner"], correctAnswer: 0 },
    { id: 273, question: "Qual è la montagna più alta del mondo?", options: ["Everest", "K2", "Kilimangiaro", "Bianco"], correctAnswer: 0 },
    { id: 274, question: "Quale città è famosa per il Carnevale e le maschere?", options: ["Venezia", "Napoli", "Firenze", "Torino"], correctAnswer: 0 },
    { id: 275, question: "Chi è considerato il padre della fisica moderna?", options: ["Isaac Newton", "Albert Einstein", "Galileo Galilei", "Tesla"], correctAnswer: 0 },
    { id: 276, question: "In quale anno è caduto il Muro di Berlino?", options: ["1989", "1991", "1985", "1945"], correctAnswer: 0 },
    { id: 277, question: "Quale continente ha più paesi?", options: ["Africa", "Asia", "Europa", "America"], correctAnswer: 0 },
    { id: 278, question: "Chi ha scritto “Il Gattopardo”?", options: ["Giuseppe Tomasi di Lampedusa", "Italo Calvino", "Luigi Pirandello", "Verga"], correctAnswer: 0 },
    { id: 279, question: "Quale oceano è il più grande?", options: ["Pacifico", "Atlantico", "Indiano", "Artico"], correctAnswer: 0 },
    { id: 280, question: "Chi ha scoperto la penicillina?", options: ["Alexander Fleming", "Louis Pasteur", "Marie Curie", "Koch"], correctAnswer: 0 },
    { id: 281, question: "Quale animale depone le uova ma non è un uccello?", options: ["Tartaruga", "Cammello", "Cavallo", "Scimmia"], correctAnswer: 0 },
    { id: 282, question: "In quale città si trova la Sagrada Familia?", options: ["Barcellona", "Madrid", "Lisbona", "Valencia"], correctAnswer: 0 },
    { id: 283, question: "Chi ha scritto “Cuore”?", options: ["Edmondo De Amicis", "Alessandro Manzoni", "Giovanni Verga", "Boccaccio"], correctAnswer: 0 },
    { id: 284, question: "Quale elemento chimico ha simbolo H?", options: ["Idrogeno", "Helio", "Hafnio", "Hg"], correctAnswer: 0 },
    { id: 285, question: "Quale città ospita il Parlamento Europeo?", options: ["Strasburgo", "Bruxelles", "Berlino", "Entrambe le prime"], correctAnswer: 3 },
    { id: 286, question: "Chi ha inventato il primo aeroplano funzionante?", options: ["Fratelli Wright", "Leonardo da Vinci", "Samuel Morse", "Bell"], correctAnswer: 0 },
    { id: 287, question: "Quale pianeta è il più grande del sistema solare?", options: ["Giove", "Saturno", "Urano", "Terra"], correctAnswer: 0 },
    { id: 288, question: "Chi ha scritto “Le avventure di Pinocchio”?", options: ["Carlo Collodi", "Gianni Rodari", "Italo Calvino", "Rodari"], correctAnswer: 0 },
    { id: 289, question: "Quale stato ha per capitale Ottawa?", options: ["Canada", "Stati Uniti", "Messico", "Australia"], correctAnswer: 0 },
    { id: 290, question: "Quale è la lingua più parlata al mondo?", options: ["Cinese mandarino", "Inglese", "Spagnolo", "Arabo"], correctAnswer: 0 },
    { id: 291, question: "Quale città è famosa per il Taj Mahal?", options: ["Agra", "Jaipur", "Delhi", "Mumbai"], correctAnswer: 0 },
    { id: 292, question: "Chi ha scritto “Fahrenheit 451”?", options: ["Ray Bradbury", "George Orwell", "Aldous Huxley", "Asimov"], correctAnswer: 0 },
    { id: 293, question: "Quale animale è simbolo dell’Australia?", options: ["Canguro", "Koala", "Emù", "Vombato"], correctAnswer: 0 },
    { id: 294, question: "Qual è il simbolo chimico dell’oro?", options: ["Au", "Ag", "Fe", "Cu"], correctAnswer: 0 },
    { id: 295, question: "Quale continente è chiamato anche “continente nero”?", options: ["Africa", "Asia", "America", "Oceania"], correctAnswer: 0 },
    { id: 296, question: "Chi ha scritto “La coscienza di Zeno”?", options: ["Italo Svevo", "Luigi Pirandello", "Giovanni Verga", "Montale"], correctAnswer: 0 },
    { id: 297, question: "Quale stato ha per capitale Lisbona?", options: ["Portogallo", "Spagna", "Italia", "Grecia"], correctAnswer: 0 },
    { id: 298, question: "Quale fiume attraversa l’Egitto?", options: ["Nilo", "Tigri", "Congo", "Gange"], correctAnswer: 0 },
    { id: 299, question: "Chi ha scritto “Moby Dick”?", options: ["Herman Melville", "Jules Verne", "Mark Twain", "London"], correctAnswer: 0 },
    { id: 300, question: "Quale città è nota come “la città eterna”?", options: ["Roma", "Atene", "Parigi", "Gerusalemme"], correctAnswer: 0 },
];
