
import { Sticker } from '../types';
import { getAsset } from './LocalAssets';

export const STICKERS_COLLECTION: Sticker[] = [
    { id: 'stk-001', name: 'Alien Cat', image: getAsset('https://loneboo-images.s3.eu-south-1.amazonaws.com/alien+cat.webp'), rarity: 'COMMON', description: 'Miao spaziale!', value: 4 },
    { id: 'stk-002', name: 'Anatra Vasino', image: getAsset('https://loneboo-images.s3.eu-south-1.amazonaws.com/anatra+vasino.webp'), rarity: 'COMMON', description: 'Pronta per il bagno.', value: 2 },
    { id: 'stk-003', name: 'Banana Surf', image: getAsset('https://loneboo-images.s3.eu-south-1.amazonaws.com/banana+surf.webp'), rarity: 'COMMON', description: 'Sulla cresta dell\'onda!', value: 3 },
    { id: 'stk-004', name: 'Cane Cono', image: getAsset('https://loneboo-images.s3.eu-south-1.amazonaws.com/cane+cono.webp'), rarity: 'COMMON', description: 'Gusto vaniglia.', value: 1 },
    { id: 'stk-005', name: 'Carota Yea', image: getAsset('https://loneboo-images.s3.eu-south-1.amazonaws.com/carota+yea.webp'), rarity: 'COMMON', description: 'Vitamina C a ritmo.', value: 2 },
    { id: 'stk-006', name: 'Dino Ballerino', image: getAsset('https://loneboo-images.s3.eu-south-1.amazonaws.com/dino+ballerino.webp'), rarity: 'COMMON', description: 'Il re della pista.', value: 4 },
    { id: 'stk-007', name: 'Faccia Di Pane', image: getAsset('https://loneboo-images.s3.eu-south-1.amazonaws.com/faccia+di+pane.webp'), rarity: 'COMMON', description: 'Morbido e simpatico.', value: 1 },
    { id: 'stk-008', name: 'Frulla Frulla', image: getAsset('https://loneboo-images.s3.eu-south-1.amazonaws.com/frulla+frulla.webp'), rarity: 'COMMON', description: 'Gira tutto!', value: 3 },
    { id: 'stk-009', name: 'Mangia Papere', image: getAsset('https://loneboo-images.s3.eu-south-1.amazonaws.com/mangia+papere.webp'), rarity: 'COMMON', description: 'Gnam gnam!', value: 2 },
    { id: 'stk-010', name: 'Color Mucca', image: getAsset('https://loneboo-images.s3.eu-south-1.amazonaws.com/mucca+arcobaleno.webp'), rarity: 'COMMON', description: 'Latte a colori.', value: 3 },
    { id: 'stk-011', name: 'Pizza Lina', image: getAsset('https://loneboo-images.s3.eu-south-1.amazonaws.com/pizza+lina.webp'), rarity: 'COMMON', description: 'Margherita felice.', value: 4 },
    { id: 'stk-012', name: 'Rana Pop', image: getAsset('https://loneboo-images.s3.eu-south-1.amazonaws.com/rana+pop.webp'), rarity: 'COMMON', description: 'Salta e canta.', value: 3 },
    { id: 'stk-013', name: 'Tazza Magna', image: getAsset('https://loneboo-images.s3.eu-south-1.amazonaws.com/tazza+magna.webpg'), rarity: 'COMMON', description: 'Colazione abbondante.', value: 2 },
    { id: 'stk-014', name: 'Wow Dog', image: getAsset('https://loneboo-images.s3.eu-south-1.amazonaws.com/wow+dog.webp'), rarity: 'COMMON', description: 'Sorpresa canina.', value: 5 },
    { id: 'stk-015', name: 'Alieno Spaghetto', image: getAsset('https://loneboo-images.s3.eu-south-1.amazonaws.com/alieno+spaghetto.webp'), rarity: 'RARE', description: 'Venuto per la pasta.', value: 5 },
    { id: 'stk-016', name: 'Baloondog', image: getAsset('https://loneboo-images.s3.eu-south-1.amazonaws.com/baloondog.webp'), rarity: 'RARE', description: 'Leggero come l\'aria.', value: 4 },
    { id: 'stk-017', name: 'Cacto Pazco', image: getAsset('https://loneboo-images.s3.eu-south-1.amazonaws.com/cacto+pazco.webp'), rarity: 'RARE', description: 'Punge ma è dolce.', value: 3 },
    { id: 'stk-018', name: 'Cervello Bolla', image: getAsset('https://loneboo-images.s3.eu-south-1.amazonaws.com/cervello+bolla.webp'), rarity: 'RARE', description: 'Idee galleggianti.', value: 4 },
    { id: 'stk-019', name: 'Gatto Sotto', image: getAsset('https://loneboo-images.s3.eu-south-1.amazonaws.com/gatto+circo.webp'), rarity: 'RARE', description: 'Miao giocoliere.', value: 5 },
    { id: 'stk-020', name: 'Hot Slime', image: getAsset('https://loneboo-images.s3.eu-south-1.amazonaws.com/hot+slime.webp'), rarity: 'RARE', description: 'Appiccicoso e caldo.', value: 6 },
    { id: 'stk-021', name: 'Ippo Patato', image: getAsset('https://loneboo-images.s3.eu-south-1.amazonaws.com/patato+ippo.webp'), rarity: 'RARE', description: 'Pesante ma tenero.', value: 3 },
    { id: 'stk-022', name: 'Piango Robo', image: getAsset('https://loneboo-images.s3.eu-south-1.amazonaws.com/piango+robo.webp'), rarity: 'RARE', description: 'Lacrime di olio.', value: 4 },
    { id: 'stk-023', name: 'Tostagatto', image: getAsset('https://loneboo-images.s3.eu-south-1.amazonaws.com/tostagatto.webp'), rarity: 'RARE', description: 'Colazione felina.', value: 5 },
    { id: 'stk-024', name: 'Trattopazzo', image: getAsset('https://loneboo-images.s3.eu-south-1.amazonaws.com/trattopazzo.webp'), rarity: 'RARE', description: 'Guida spericolata.', value: 4 },
    { id: 'stk-025', name: 'Astro Us', image: getAsset('https://loneboo-images.s3.eu-south-1.amazonaws.com/astro+us.webp'), rarity: 'EPIC', description: 'Esploratore galattico.', value: 5 },
    { id: 'stk-026', name: 'Piovro Bubble', image: getAsset('https://loneboo-images.s3.eu-south-1.amazonaws.com/piovro+bubble.webp'), rarity: 'EPIC', description: 'Otto braccia di bolle.', value: 4 },
    { id: 'stk-027', name: 'Roblospino', image: getAsset('https://loneboo-images.s3.eu-south-1.amazonaws.com/roblospino.webp'), rarity: 'EPIC', description: 'Tecnologia pungente.', value: 5 },
    { id: 'stk-028', name: 'Rotocatto', image: getAsset('https://loneboo-images.s3.eu-south-1.amazonaws.com/rotocatto.webp'), rarity: 'EPIC', description: 'Gatto a motore.', value: 5 },
    { id: 'stk-029', name: 'Scappa Drin', image: getAsset('https://loneboo-images.s3.eu-south-1.amazonaws.com/scappa+drin.webp'), rarity: 'LEGENDARY', description: 'La sveglia più veloce.', value: 6 },
    { id: 'stk-030', name: 'Super Banano', image: getAsset('https://loneboo-images.s3.eu-south-1.amazonaws.com/super+banano.webp'), rarity: 'LEGENDARY', description: 'L\'eroe della frutta.', value: 7 }
];

export const STICKERS_COLLECTION_VOL2: Sticker[] = [
    { id: 'stk2-001', name: 'Albero Dei Coni', image: getAsset('https://loneboo-images.s3.eu-south-1.amazonaws.com/albero+dei+coni.webp'), rarity: 'COMMON', description: 'Gelati che crescono sui rami!', value: 4 },
    { id: 'stk2-002', name: 'Autoban', image: getAsset('https://loneboo-images.s3.eu-south-1.amazonaws.com/autoban.webp'), rarity: 'COMMON', description: 'Non parcheggiare qui!', value: 3 },
    { id: 'stk2-003', name: 'Baby Dino', image: getAsset('https://loneboo-images.s3.eu-south-1.amazonaws.com/baby+dino.webp'), rarity: 'COMMON', description: 'Piccolo ma ruggente.', value: 4 },
    { id: 'stk2-004', name: 'Banaphone', image: getAsset('https://loneboo-images.s3.eu-south-1.amazonaws.com/bana+phone.webp'), rarity: 'COMMON', description: 'Pronto? Chi parla?', value: 2 },
    { id: 'stk2-005', name: 'Biscognam', image: getAsset('https://loneboo-images.s3.eu-south-1.amazonaws.com/biscognam.webp'), rarity: 'COMMON', description: 'Croccante e dolce.', value: 3 },
    { id: 'stk2-006', name: 'Calzino Curioso', image: getAsset('https://loneboo-images.s3.eu-south-1.amazonaws.com/calzino+curioso.webp'), rarity: 'COMMON', description: 'Dove sarà il compagno?', value: 2 },
    { id: 'stk2-007', name: 'Canta Wc', image: getAsset('https://loneboo-images.s3.eu-south-1.amazonaws.com/canta+wc.webp'), rarity: 'COMMON', description: 'Opera sotto la doccia.', value: 3 },
    { id: 'stk2-008', name: 'Cuscino Sveglino', image: getAsset('https://loneboo-images.s3.eu-south-1.amazonaws.com/cuscino+sveglino.webp'), rarity: 'COMMON', description: 'Non ti fa mai dormire.', value: 3 },
    { id: 'stk2-009', name: 'Zuppa Pazza', image: getAsset('https://loneboo-images.s3.eu-south-1.amazonaws.com/fagioli+pazzi.webp'), rarity: 'COMMON', description: 'Ingredienti segreti e matti.', value: 4 },
    { id: 'stk2-010', name: 'Fizzy Pop', image: getAsset('https://loneboo-images.s3.eu-south-1.amazonaws.com/fizzy+pop.webp'), rarity: 'COMMON', description: 'Frizzante come non mai.', value: 5 },
    { id: 'stk2-011', name: 'Galla Nonna', image: getAsset('https://loneboo-images.s3.eu-south-1.amazonaws.com/galla+nonna.webp'), rarity: 'COMMON', description: 'Galleggia con stile.', value: 4 },
    { id: 'stk2-012', name: 'Gommo Dino', image: getAsset('https://loneboo-images.s3.eu-south-1.amazonaws.com/gommo+dino.webp'), rarity: 'COMMON', description: 'Rimbalza ovunque.', value: 5 },
    { id: 'stk2-013', name: 'Mela Penso', image: getAsset('https://loneboo-images.s3.eu-south-1.amazonaws.com/mela-penso.webp'), rarity: 'COMMON', description: 'Un frutto filosofico.', value: 3 },
    { id: 'stk2-014', name: 'Orsetto Confetto', image: getAsset('https://loneboo-images.s3.eu-south-1.amazonaws.com/orsetto+confetto.webp'), rarity: 'COMMON', description: 'Dolce da morire.', value: 4 },
    { id: 'stk2-015', name: 'Alien Ice', image: getAsset('https://loneboo-images.s3.eu-south-1.amazonaws.com/alien+ice.webp'), rarity: 'RARE', description: 'Ghiacciolo venuto dallo spazio.', value: 6 },
    { id: 'stk2-016', name: 'Bimbo Boom', image: getAsset('https://loneboo-images.s3.eu-south-1.amazonaws.com/bimbo+boom.webp'), rarity: 'RARE', description: 'Un\'esplosione di allegria.', value: 5 },
    { id: 'stk2-017', name: 'Blocco Re', image: getAsset('https://loneboo-images.s3.eu-south-1.amazonaws.com/blocco+re.webp'), rarity: 'RARE', description: 'Il sovrano dei mattoncini.', value: 5 },
    { id: 'stk2-018', name: 'Burger King', image: getAsset('https://loneboo-images.s3.eu-south-1.amazonaws.com/burger+king.webp'), rarity: 'RARE', description: 'Il panino reale.', value: 5 },
    { id: 'stk2-019', name: 'Fiorebot', image: getAsset('https://loneboo-images.s3.eu-south-1.amazonaws.com/fiorebot.webp'), rarity: 'RARE', description: 'Natura tecnologica.', value: 4 },
    { id: 'stk2-020', name: 'Gnocchi Glitch', image: getAsset('https://loneboo-images.s3.eu-south-1.amazonaws.com/gnocchi+glitch.webp'), rarity: 'RARE', description: 'Pasta digitale.', value: 4 },
    { id: 'stk2-021', name: 'Lumaca Baleno', image: getAsset('https://loneboo-images.s3.eu-south-1.amazonaws.com/lumaca+baleno.webp'), rarity: 'RARE', description: 'Più veloce della luce.', value: 5 },
    { id: 'stk2-022', name: 'Nuvola Ciambellosa', image: getAsset('https://loneboo-images.s3.eu-south-1.amazonaws.com/nuvola+ciambellosa.webp'), rarity: 'RARE', description: 'Soffice e zuccherosa.', value: 3 },
    { id: 'stk2-023', name: 'Pastellante', image: getAsset('https://loneboo-images.s3.eu-south-1.amazonaws.com/pastellante.webp'), rarity: 'RARE', description: 'Colora il mondo.', value: 4 },
    { id: 'stk2-024', name: 'Pizza Express', image: getAsset('https://loneboo-images.s3.eu-south-1.amazonaws.com/pizza+express.webp'), rarity: 'RARE', description: 'Consegna in 3 secondi.', value: 6 },
    { id: 'stk2-025', name: 'Discoiattolo', image: getAsset('https://loneboo-images.s3.eu-south-1.amazonaws.com/discoiattolo.webp'), rarity: 'EPIC', description: 'Il re della pista da ballo.', value: 6 },
    { id: 'stk2-026', name: 'Glitchy Boo', image: getAsset('https://loneboo-images.s3.eu-south-1.amazonaws.com/glitchy+boo.webp'), rarity: 'EPIC', description: 'Un errore nel sistema fantasma.', value: 7 },
    { id: 'stk2-027', name: 'Lampo Di Genio', image: getAsset('https://loneboo-images.s3.eu-south-1.amazonaws.com/lampo+di+genio.webp'), rarity: 'EPIC', description: 'Un\'idea brillante!', value: 6 },
    { id: 'stk2-028', name: 'Rocket Pio', image: getAsset('https://loneboo-images.s3.eu-south-1.amazonaws.com/rocket+pio.webp'), rarity: 'EPIC', description: 'Pulcino spaziale.', value: 5 },
    { id: 'stk2-029', name: 'Pazzo Boo', image: getAsset('https://loneboo-images.s3.eu-south-1.amazonaws.com/pazzo+boo.webp'), rarity: 'LEGENDARY', description: 'Il fantasma più matto di tutti!', value: 8 },
    { id: 'stk2-030', name: 'Taco Gatto', image: getAsset('https://loneboo-images.s3.eu-south-1.amazonaws.com/taco+gatto.webp'), rarity: 'LEGENDARY', description: 'Miao! Salsa piccante inclusa.', value: 9 }
];
