
import { Sticker } from '../types';
import { getAsset } from './LocalAssets';

export const STICKERS_COLLECTION: Sticker[] = [
    { id: 'stk-001', name: 'Alien Cat', image: getAsset('https://i.postimg.cc/50VPD1Yk/alien-cat.jpg'), rarity: 'COMMON', description: 'Miao spaziale!' },
    { id: 'stk-002', name: 'Anatra Vasino', image: getAsset('https://i.postimg.cc/Nj2pMLRZ/anatra-vasino.jpg'), rarity: 'COMMON', description: 'Pronta per il bagno.' },
    { id: 'stk-003', name: 'Banana Surf', image: getAsset('https://i.postimg.cc/5tq5Yzy2/banana-surf.jpg'), rarity: 'COMMON', description: 'Sulla cresta dell\'onda!' },
    { id: 'stk-004', name: 'Cane Cono', image: getAsset('https://i.postimg.cc/FH038Sjg/cane-cono.jpg'), rarity: 'COMMON', description: 'Gusto vaniglia.' },
    { id: 'stk-005', name: 'Carota Yea', image: getAsset('https://i.postimg.cc/d1NyrjYd/carota-yea.jpg'), rarity: 'COMMON', description: 'Vitamina C a ritmo.' },
    { id: 'stk-006', name: 'Dino Ballerino', image: getAsset('https://i.postimg.cc/k4H2BMQS/dino-ballerino.jpg'), rarity: 'COMMON', description: 'Il re della pista.' },
    { id: 'stk-007', name: 'Faccia Di Pane', image: getAsset('https://i.postimg.cc/8kqbYN2D/faccia-di-pane.jpg'), rarity: 'COMMON', description: 'Morbido e simpatico.' },
    { id: 'stk-008', name: 'Frulla Frulla', image: getAsset('https://i.postimg.cc/cJ9RBS7n/frulla-frulla.jpg'), rarity: 'COMMON', description: 'Gira tutto!' },
    { id: 'stk-009', name: 'Mangia Papere', image: getAsset('https://i.postimg.cc/MKmjYwqS/mangia-papere.jpg'), rarity: 'COMMON', description: 'Gnam gnam!' },
    { id: 'stk-010', name: 'Color Mucca', image: getAsset('https://i.postimg.cc/6p1qH5Pz/mucca-arcobaleno.jpg'), rarity: 'COMMON', description: 'Latte a colori.' },
    { id: 'stk-011', name: 'Pizza Lina', image: getAsset('https://i.postimg.cc/Pr5dBn1L/pizza-lina.jpg'), rarity: 'COMMON', description: 'Margherita felice.' },
    { id: 'stk-012', name: 'Rana Pop', image: getAsset('https://i.postimg.cc/ydTzbLdW/rana-pop.jpg'), rarity: 'COMMON', description: 'Salta e canta.' },
    { id: 'stk-013', name: 'Tazza Magna', image: getAsset('https://i.postimg.cc/qR15KSqt/tazza-magna.jpg'), rarity: 'COMMON', description: 'Colazione abbondante.' },
    { id: 'stk-014', name: 'Wow Dog', image: getAsset('https://i.postimg.cc/brKLHhh0/wow-dog.jpg'), rarity: 'COMMON', description: 'Sorpresa canina.' },
    { id: 'stk-015', name: 'Alieno Spaghetto', image: getAsset('https://i.postimg.cc/L5yNq1CF/alieno-spaghetto.jpg'), rarity: 'RARE', description: 'Venuto per la pasta.' },
    { id: 'stk-016', name: 'Baloondog', image: getAsset('https://i.postimg.cc/kMjcvWcz/baloondog.jpg'), rarity: 'RARE', description: 'Leggero come l\'aria.' },
    { id: 'stk-017', name: 'Cacto Pazco', image: getAsset('https://i.postimg.cc/qqg25ZLW/cacto-pazco.jpg'), rarity: 'RARE', description: 'Punge ma è dolce.' },
    { id: 'stk-018', name: 'Cervello Bolla', image: getAsset('https://i.postimg.cc/pLQ5qHH4/cervello-bolla.jpg'), rarity: 'RARE', description: 'Idee galleggianti.' },
    { id: 'stk-019', name: 'Gatto Sotto', image: getAsset('https://i.postimg.cc/MK2yDtBB/gatto-circo.jpg'), rarity: 'RARE', description: 'Miao giocoliere.' },
    { id: 'stk-020', name: 'Hot Slime', image: getAsset('https://i.postimg.cc/hvF72PXB/hot-slime.jpg'), rarity: 'RARE', description: 'Appiccicoso e caldo.' },
    { id: 'stk-021', name: 'Ippo Patato', image: getAsset('https://i.postimg.cc/pd49dXY8/patato-ippo.jpg'), rarity: 'RARE', description: 'Pesante ma tenero.' },
    { id: 'stk-022', name: 'Piango Robo', image: getAsset('https://i.postimg.cc/mkw27bM7/piango-robo.jpg'), rarity: 'RARE', description: 'Lacrime di olio.' },
    { id: 'stk-023', name: 'Tostagatto', image: getAsset('https://i.postimg.cc/h43YPkH7/tostagatto.jpg'), rarity: 'RARE', description: 'Colazione felina.' },
    { id: 'stk-024', name: 'Trattopazzo', image: getAsset('https://i.postimg.cc/6Q0jsgr6/trattopazzo.jpg'), rarity: 'RARE', description: 'Guida spericolata.' },
    { id: 'stk-025', name: 'Astro Us', image: getAsset('https://i.postimg.cc/fLCvFdhL/astro-us.jpg'), rarity: 'EPIC', description: 'Esploratore galattico.' },
    { id: 'stk-026', name: 'Piovro Bubble', image: getAsset('https://i.postimg.cc/RF1MzMP0/piovro-bubble.jpg'), rarity: 'EPIC', description: 'Otto braccia di bolle.' },
    { id: 'stk-027', name: 'Roblospino', image: getAsset('https://i.postimg.cc/NGpc8CZg/roblospino.jpg'), rarity: 'EPIC', description: 'Tecnologia pungente.' },
    { id: 'stk-028', name: 'Rotocatto', image: getAsset('https://i.postimg.cc/FK55FMkY/rotocatto.jpg'), rarity: 'EPIC', description: 'Gatto a motore.' },
    { id: 'stk-029', name: 'Scappa Drin', image: getAsset('https://i.postimg.cc/HnLFPHR3/scappa-drin.jpg'), rarity: 'LEGENDARY', description: 'La sveglia più veloce.' },
    { id: 'stk-030', name: 'Super Banano', image: getAsset('https://i.postimg.cc/RZtyYgpx/super-banano.jpg'), rarity: 'LEGENDARY', description: 'L\'eroe della frutta.' }
];

export const STICKERS_COLLECTION_VOL2: Sticker[] = [
    { id: 'stk2-001', name: 'Albero Dei Coni', image: getAsset('https://i.postimg.cc/6q38w0pv/albero-dei-coni.jpg'), rarity: 'COMMON', description: 'Gelati che crescono sui rami!' },
    { id: 'stk2-002', name: 'Autoban', image: getAsset('https://i.postimg.cc/GpC99rp3/autoban.jpg'), rarity: 'COMMON', description: 'Non parcheggiare qui!' },
    { id: 'stk2-003', name: 'Baby Dino', image: getAsset('https://i.postimg.cc/GtHm6mXC/baby-dino.jpg'), rarity: 'COMMON', description: 'Piccolo ma ruggente.' },
    { id: 'stk2-004', name: 'Banaphone', image: getAsset('https://i.postimg.cc/654Q0T7V/bana-phone.jpg'), rarity: 'COMMON', description: 'Pronto? Chi parla?' },
    { id: 'stk2-005', name: 'Biscognam', image: getAsset('https://i.postimg.cc/1zBRtqTH/biscognam.jpg'), rarity: 'COMMON', description: 'Croccante e dolce.' },
    { id: 'stk2-006', name: 'Calzino Curioso', image: getAsset('https://i.postimg.cc/yNLBBzgp/calzino-curioso.jpg'), rarity: 'COMMON', description: 'Dove sarà il compagno?' },
    { id: 'stk2-007', name: 'Canta Wc', image: getAsset('https://i.postimg.cc/0jwqpMtM/canta-wc.jpg'), rarity: 'COMMON', description: 'Opera sotto la doccia.' },
    { id: 'stk2-008', name: 'Cuscino Sveglino', image: getAsset('https://i.postimg.cc/VsxJ2jPZ/cuscino-sveglino.jpg'), rarity: 'COMMON', description: 'Non ti fa mai dormire.' },
    { id: 'stk2-009', name: 'Zuppa Pazza', image: getAsset('https://i.postimg.cc/zXYfx8ny/fagioli-pazzi.jpg'), rarity: 'COMMON', description: 'Ingredienti segreti e matti.' },
    { id: 'stk2-010', name: 'Fizzy Pop', image: getAsset('https://i.postimg.cc/TYT6ywVg/fizzy-pop.jpg'), rarity: 'COMMON', description: 'Frizzante come non mai.' },
    { id: 'stk2-011', name: 'Galla Nonna', image: getAsset('https://i.postimg.cc/6Q4JsGKX/galla-nonna.jpg'), rarity: 'COMMON', description: 'Galleggia con stile.' },
    { id: 'stk2-012', name: 'Gommo Dino', image: getAsset('https://i.postimg.cc/3xybW5c0/gommo-dino.jpg'), rarity: 'COMMON', description: 'Rimbalza ovunque.' },
    { id: 'stk2-013', name: 'Mela Penso', image: getAsset('https://i.postimg.cc/FHJDNbYG/mela-penso.jpg'), rarity: 'COMMON', description: 'Un frutto filosofico.' },
    { id: 'stk2-014', name: 'Orsetto Confetto', image: getAsset('https://i.postimg.cc/G2zjqqfT/orsetto-confetto.jpg'), rarity: 'COMMON', description: 'Dolce da morire.' },
    { id: 'stk2-015', name: 'Alien Ice', image: getAsset('https://i.postimg.cc/7Yj58Svp/alien-ice.jpg'), rarity: 'RARE', description: 'Ghiacciolo venuto dallo spazio.' },
    { id: 'stk2-016', name: 'Bimbo Boom', image: getAsset('https://i.postimg.cc/L8z6c73t/bimbo-boom.jpg'), rarity: 'RARE', description: 'Un\'esplosione di allegria.' },
    { id: 'stk2-017', name: 'Blocco Re', image: getAsset('https://i.postimg.cc/fyGDFjtz/blocco-re.jpg'), rarity: 'RARE', description: 'Il sovrano dei mattoncini.' },
    { id: 'stk2-018', name: 'Burger King', image: getAsset('https://i.postimg.cc/0yq90n1C/burger-king.jpg'), rarity: 'RARE', description: 'Il panino reale.' },
    { id: 'stk2-019', name: 'Fiorebot', image: getAsset('https://i.postimg.cc/Nftg1bc5/fiorebot.jpg'), rarity: 'RARE', description: 'Natura tecnologica.' },
    { id: 'stk2-020', name: 'Gnocchi Glitch', image: getAsset('https://i.postimg.cc/FRX62WGf/gnocchi-glitch.jpg'), rarity: 'RARE', description: 'Pasta digitale.' },
    { id: 'stk2-021', name: 'Lumaca Baleno', image: getAsset('https://i.postimg.cc/sx6wDw9C/lumaca-baleno.jpg'), rarity: 'RARE', description: 'Più veloce della luce.' },
    { id: 'stk2-022', name: 'Nuvola Ciambellosa', image: getAsset('https://i.postimg.cc/PqWy8tzK/nuvola-ciambellosa.jpg'), rarity: 'RARE', description: 'Soffice e zuccherosa.' },
    { id: 'stk2-023', name: 'Pastellante', image: getAsset('https://i.postimg.cc/J76qXYJj/pastellante.jpg'), rarity: 'RARE', description: 'Colora il mondo.' },
    { id: 'stk2-024', name: 'Pizza Express', image: getAsset('https://i.postimg.cc/zGWS9JM5/pizza-express.jpg'), rarity: 'RARE', description: 'Consegna in 3 secondi.' },
    { id: 'stk2-025', name: 'Discoiattolo', image: getAsset('https://i.postimg.cc/sgc1BqGZ/discoiattolo.jpg'), rarity: 'EPIC', description: 'Il re della pista da ballo.' },
    { id: 'stk2-026', name: 'Glitchy Boo', image: getAsset('https://i.postimg.cc/mkR0FXHk/glitchy-boo.jpg'), rarity: 'EPIC', description: 'Un errore nel sistema fantasma.' },
    { id: 'stk2-027', name: 'Lampo Di Genio', image: getAsset('https://i.postimg.cc/QtD66Bx4/lampo-di-genio.jpg'), rarity: 'EPIC', description: 'Un\'idea brillante!' },
    { id: 'stk2-028', name: 'Rocket Pio', image: getAsset('https://i.postimg.cc/3RrX42xz/rocket-pio.jpg'), rarity: 'EPIC', description: 'Pulcino spaziale.' },
    { id: 'stk2-029', name: 'Pazzo Boo', image: getAsset('https://i.postimg.cc/wTnQftwv/pazzo-boo.jpg'), rarity: 'LEGENDARY', description: 'Il fantasma più matto di tutti!' },
    { id: 'stk2-030', name: 'Taco Gatto', image: getAsset('https://i.postimg.cc/NF5RbYTb/taco-gatto.jpg'), rarity: 'LEGENDARY', description: 'Miao! Salsa piccante inclusa.' }
];
